version: '3'
services:
  user-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/users?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
