version: "3"
services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/users?authSource=admin
    depends_on:
      - mongodb

  # task-service:
  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "3002:3000"
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/users?authSource=admin
    depends_on:
      - mongodb
  # task-service:

  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
